<?php

/**
 * @file
 * Contains detailsfilter.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function detailsfilter_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the detailsfilter module.
    case 'help.page.detailsfilter':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Provides a details text filter.') . '</p>';
      return $output;

    default:
  }
}
